### ISSUE TITLE
Multiple line breaks break content

### ISSUE THREAD

**Issue by TheAlexLichter** [flexdinesh/tweet-fancy#2]
![image](https://user-images.githubusercontent.com/640208/50912553-53493780-142a-11e9-9885-c4b11ca4828f.png)

**Comment by flexdinesh** [comment]
Thanks @manniL . I've pushed a quick fix for this. This should do for now. 6b1d795

**Comment by TheAlexLichter** [comment]
@flexdinesh Fixed the problem only partly ☺️ 

IMO you should still be able to add line breaks ("as many as you want"). Currently they are stripped.

But you already noted that down.

**Comment by flexdinesh** [comment]
8fcc2ed fixes this
